export const Cities = [
  {
    city: 'Amman',
    lat: '31.9500',
    lng: '35.9333',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'primary',
    population: '4007526',
    population_proper: '4007526'
  },
  {
    city: 'Irbid',
    lat: '32.5556',
    lng: '35.8500',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'admin',
    population: '1088100',
    population_proper: '1088100'
  },
  {
    city: 'Az Zarqā’',
    lat: '32.0833',
    lng: '36.1000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'admin',
    population: '481300',
    population_proper: '481300'
  },
  {
    city: 'Al ‘Aqabah',
    lat: '29.5167',
    lng: '35.0000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Aqabah',
    capital: 'admin',
    population: '140000',
    population_proper: '140000'
  },
  {
    city: 'As Salţ',
    lat: '32.0333',
    lng: '35.7333',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'admin',
    population: '88900',
    population_proper: '88900'
  },
  {
    city: 'Al Mafraq',
    lat: '32.2833',
    lng: '36.2333',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'admin',
    population: '57118',
    population_proper: '57118'
  },
  {
    city: 'Jarash',
    lat: '32.2723',
    lng: '35.8914',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Jarash',
    capital: 'admin',
    population: '50745',
    population_proper: '50745'
  },
  {
    city: 'Ma‘ān',
    lat: '30.1920',
    lng: '35.7360',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'admin',
    population: '50350',
    population_proper: '50350'
  },
  {
    city: 'Aţ Ţurrah',
    lat: '32.6368',
    lng: '35.9900',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: '',
    population: '34948',
    population_proper: '34948'
  },
  {
    city: 'Aţ Ţafīlah',
    lat: '30.8375',
    lng: '35.6042',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Aţ Ţafīlah',
    capital: 'admin',
    population: '25429',
    population_proper: '25429'
  },
  {
    city: 'Al Karak',
    lat: '31.1833',
    lng: '35.7000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'admin',
    population: '21678',
    population_proper: '21678'
  },
  {
    city: 'Al ‘Abdallī',
    lat: '31.9650',
    lng: '35.9082',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ar Ruşayfah',
    lat: '32.0178',
    lng: '36.0464',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Mārkā',
    lat: '31.9863',
    lng: '35.9965',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Jubayhah',
    lat: '32.0256',
    lng: '35.8644',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Juwayyidah',
    lat: '31.9167',
    lng: '35.9500',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Mādabā',
    lat: '31.7167',
    lng: '35.8000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'admin',
    population: '',
    population_proper: ''
  },
  {
    city: '‘Ajlūn',
    lat: '32.3325',
    lng: '35.7517',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: '‘Ajlūn',
    capital: 'admin',
    population: '',
    population_proper: ''
  },
  {
    city: '‘Ayn al Bāshā',
    lat: '32.0573',
    lng: '35.8311',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Wādī as Sīr',
    lat: '31.9545',
    lng: '35.8183',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Fuḩayş',
    lat: '32.0047',
    lng: '35.7809',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Mazār ash Shamālī',
    lat: '32.4704',
    lng: '35.7969',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Kafr Asad',
    lat: '32.5980',
    lng: '35.7127',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Ḩişn',
    lat: '32.4845',
    lng: '35.8841',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Dayr Abū Sa‘īd',
    lat: '32.4982',
    lng: '35.6867',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Aţ Ţayyibah',
    lat: '32.5430',
    lng: '35.7176',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ash Shūnah ash Shamālīyah',
    lat: '32.6100',
    lng: '35.6080',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Nā‘ūr',
    lat: '31.8744',
    lng: '35.8247',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: '‘Irjān',
    lat: '32.3945',
    lng: '35.7334',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: '‘Ajlūn',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ar Ramthā',
    lat: '32.5592',
    lng: '36.0069',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Muthallath Jāmi‘at Āl al Bayt',
    lat: '32.3459',
    lng: '36.2335',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Kufrinjah',
    lat: '32.3000',
    lng: '35.7000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: '‘Ajlūn',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Hāshimīyah',
    lat: '32.1333',
    lng: '36.1167',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Sammā ar Rawsān',
    lat: '32.6379',
    lng: '35.8266',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Irbid',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Şakhrah',
    lat: '32.3709',
    lng: '35.8427',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: '‘Ajlūn',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Maşţabah',
    lat: '32.1843',
    lng: '35.8559',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Jarash',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Juraynah',
    lat: '31.7667',
    lng: '35.8000',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Manshīyat Banī Ḩasan',
    lat: '32.3707',
    lng: '36.0793',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ḩisbān',
    lat: '31.7982',
    lng: '35.8099',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: '‘Allān',
    lat: '32.1182',
    lng: '35.7435',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Umm al Basātīn',
    lat: '31.8245',
    lng: '35.8779',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Dayr ‘Allā',
    lat: '32.1889',
    lng: '35.6031',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Khālidīyah',
    lat: '32.1790',
    lng: '36.3033',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: '‘Ayy',
    lat: '31.1337',
    lng: '35.6437',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Samā as Sirḩān',
    lat: '32.4686',
    lng: '36.2436',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Az̧ Z̧ulayl',
    lat: '32.1208',
    lng: '36.2801',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ash Shūnah al Janūbīyah',
    lat: '31.8915',
    lng: '35.6178',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Mazār al Janūbī',
    lat: '31.0672',
    lng: '35.6949',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Umm al Jimāl',
    lat: '32.3286',
    lng: '36.3679',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Ḩusaynīyah',
    lat: '31.0261',
    lng: '35.7229',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Bal‘amā',
    lat: '32.2365',
    lng: '36.0881',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Mulayḩ',
    lat: '31.5881',
    lng: '35.8125',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Fuqū‘',
    lat: '31.3681',
    lng: '35.7022',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Irḩāb',
    lat: '32.3234',
    lng: '36.0909',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Burmā',
    lat: '32.2193',
    lng: '35.7851',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Jarash',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Aş Şubayḩī',
    lat: '32.1484',
    lng: '35.7053',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ḩawshā',
    lat: '32.4514',
    lng: '36.0990',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Saḩāb',
    lat: '31.8703',
    lng: '36.0048',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Wādī Mūsá',
    lat: '30.3289',
    lng: '35.4403',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Fayşalīyah',
    lat: '31.7491',
    lng: '35.7692',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Qaşr',
    lat: '31.3141',
    lng: '35.7439',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Umm al Qiţţayn',
    lat: '32.3145',
    lng: '36.6283',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Yarqā',
    lat: '31.9758',
    lng: '35.6964',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Balqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Bīrayn',
    lat: '32.0994',
    lng: '35.9578',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Buşayrā',
    lat: '30.7326',
    lng: '35.6094',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Aţ Ţafīlah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Mughayyir',
    lat: '31.4063',
    lng: '35.7708',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ghawr aş Şāfī',
    lat: '31.0369',
    lng: '35.4877',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Rujm ash Shāmī al Gharbī',
    lat: '31.8333',
    lng: '36.0167',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Şabḩā',
    lat: '32.3270',
    lng: '36.5016',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Dhībān',
    lat: '31.4989',
    lng: '35.7829',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Mā‘īn',
    lat: '31.6800',
    lng: '35.7320',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ayl',
    lat: '30.2059',
    lng: '35.5363',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Muwaqqar',
    lat: '31.8147',
    lng: '36.1088',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ghawr al Mazra‘ah',
    lat: '31.2659',
    lng: '35.5167',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ash Shawbak',
    lat: '30.5213',
    lng: '35.5714',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Dayr al Kahf',
    lat: '32.2753',
    lng: '36.8395',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al ‘Arīḑ',
    lat: '31.5584',
    lng: '35.6574',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma’dabā',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Adhruḩ',
    lat: '30.3281',
    lng: '35.5986',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Muthallath Şabḩā',
    lat: '32.2601',
    lng: '36.4678',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Ḩusaynīyah',
    lat: '30.5955',
    lng: '35.7970',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Jīzah',
    lat: '31.6989',
    lng: '35.9553',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Ḩasā',
    lat: '30.8213',
    lng: '35.9750',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Aţ Ţafīlah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Murayghah',
    lat: '30.0953',
    lng: '35.5231',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Quwayrah',
    lat: '29.8047',
    lng: '35.3111',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Aqabah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ad Dīsah',
    lat: '29.6528',
    lng: '35.5112',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Aqabah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Qaţrānah',
    lat: '31.2508',
    lng: '36.0493',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Karak',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Umm ar Raşāş',
    lat: '31.5122',
    lng: '35.9184',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Āşimah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Muthallath al Azraq',
    lat: '31.8327',
    lng: '36.8149',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Az Zarqā’',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ar Rīshah',
    lat: '30.2243',
    lng: '35.2167',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al ‘Aqabah',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Ar Ruwayshid',
    lat: '32.5015',
    lng: '38.2040',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Al Mafraq',
    capital: 'minor',
    population: '',
    population_proper: ''
  },
  {
    city: 'Al Jafr',
    lat: '30.3184',
    lng: '36.1777',
    country: 'Jordan',
    iso2: 'JO',
    admin_name: 'Ma‘ān',
    capital: 'minor',
    population: '',
    population_proper: ''
  }
];
